### ISSUE TITLE
Alert dialog opens up even on valid input

### ISSUE THREAD

**Issue by dkp1903** [rutikwankhade/Finman#1]
A fix would be to check why control goes to the else block. Also, we can do better than `alert()` to handle the invalid input. Kindly allow me to work on it.

**Comment by rutikwankhade** [comment]
Yes please go ahead.

**Comment by dkp1903** [comment]
Made a PR - it was a lil typo.

**Comment by dkp1903** [comment]
There's something weird happening - unpredictably gives the error when I use tab - enter to enter a set of inputs, even though they are valid. I think we can disregard this case - hope that users only use tab-space or mouse to enter inputs
