### ISSUE TITLE
Need to open Media Query for tab mode,as i figured it's not working perfectly in different tab size

### ISSUE THREAD

**Issue by Keshav04042001** [rutikwankhade/Finman#3]
![Screenshot (414)](https://user-images.githubusercontent.com/56186828/103472022-047ed000-4dae-11eb-8dd3-34e2b245e1b1.png)

**Comment by Keshav04042001** [comment]
will you please allow me to fix that

**Comment by rutikwankhade** [comment]
@Keshav04042001 Yes please 🙌 Go ahead.

**Comment by Keshav04042001** [comment]
Thanks mr.rutik for allowing me to work,I made few changes accordingly,please have a look,i wish it will meet your expectation.If not please let me know,I'll work more.

![Screenshot (417)](https://user-images.githubusercontent.com/56186828/103479119-6d3b6c00-4df1-11eb-944d-ddc968525d8c.png)
![Screenshot (416)](https://user-images.githubusercontent.com/56186828/103479120-73314d00-4df1-11eb-93da-baf537a2d76c.png)
![Screenshot (415)](https://user-images.githubusercontent.com/56186828/103479122-775d6a80-4df1-11eb-9732-ef789372f78e.png)

**Comment by rutikwankhade** [comment]
👏 awesome. This is more than perfect.
